@startuml
class User{
}

object Goal
object Admin
object MonthlyLicense
object YearLicense
object Course
object Certificate
object Material
object License


Goal o-down-User
User -down-o License
User -left-o Certificate
Course o-left- User


License <|-down- MonthlyLicense
License <|-down-  YearLicense

Course <|-right- Material

License <|-right- Admin
Course <|-down- Admin

@enduml