@startuml
class User{
}

object Login
object Admin
object Single_Course_Licence
object Full_Course_Licence
object Course
object Certificate
object Material
object License
object Curriculum
object ListOfCourses


ListOfCourses o-down-User
User -down-o License
User -left-o Certificate
Course o-left- User


License <|-down- Single_Course_Licence
License <|-down-  Full_Course_Licence

Course <|-right- Material

License -right- Admin
Certificate -right- Admin
Curriculum -down- Admin
Material -down-o Curriculum
Course -down-o Curriculum

@enduml